name: tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v4
      - name: Setup Node (for bibtex-tidy)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install bibtex-tidy
        run: npm install -g bibtex-tidy
      - name: Install tectonic
        run: url --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net |sh
      - run: uv run pytest
